Repository enpayne/agile-assessment-tool, pull requests merged in 2019-06, with the labels that each got.

#57 Use BD and Agile profile links
  client/src/app/result/profile/Profile.js
  client/src/app/result/profile/profileInformation.js
  client/src/app/result/profile/profiles.js
  client/src/assets/images/profile/kiky.jpeg
  e2e/cypress/integration/complete_survey.js
Labels: enhancement

#58 Cleanup component hierarchy
  client/src/App.js
  client/src/app/result/link/Link.js
  client/src/app/result/link/linkProvider.js
  client/src/app/surveyconfig/QuestionType.js
  client/src/assets/images/spinner.gif
  client/src/assets/links.js
  client/src/assets/profiles.js
  client/src/assets/scoreDescriptors.js
  client/src/components/AgileAssessment.js
  client/src/components/FootNote.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Result/Evaluation.js
  client/src/components/Result/Evaluation.react.test.js
  client/src/components/Result/Feedback.js
  client/src/components/Result/Feedback.react.test.js
  client/src/components/Result/Link.js
  client/src/components/Result/Link.react..test.js
  client/src/components/Result/Profile.js
  client/src/components/Result/index.js
  client/src/config/api.js
  client/src/config/registerServiceWorker.js
  client/src/config/surveyConfig.js
  client/src/config/surveyConfig.test.js
  client/src/index.js
  client/src/styles/index.scss
  client/src/utils/feedbackValidator.js
  client/src/utils/feedbackValidator.test.js
  client/src/utils/scoreEvaluator.js
  client/src/utils/scoreEvaluator.test.js
Labels: cleanup

#59 Release/v1.2.1
  client/src/App.js
  client/src/app/result/link/Link.js
  client/src/app/result/link/linkProvider.js
  client/src/app/result/profile/Profile.js
  client/src/app/result/profile/profileInformation.js
  client/src/app/surveyconfig/QuestionType.js
  client/src/assets/images/profile/kiky.jpeg
  client/src/assets/images/spinner.gif
  client/src/assets/links.js
  client/src/assets/profiles.js
  client/src/assets/scoreDescriptors.js
  client/src/components/AgileAssessment.js
  client/src/components/FootNote.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Result/Evaluation.js
  client/src/components/Result/Evaluation.react.test.js
  client/src/components/Result/Feedback.js
  client/src/components/Result/Feedback.react.test.js
  client/src/components/Result/Link.js
  client/src/components/Result/Link.react..test.js
  client/src/components/Result/Profile.js
  client/src/components/Result/index.js
  client/src/config/api.js
  client/src/config/registerServiceWorker.js
  client/src/config/surveyConfig.js
  client/src/config/surveyConfig.test.js
  client/src/index.js
  client/src/styles/evaluation.scss
  client/src/styles/index.scss
  client/src/styles/result.scss
  client/src/utils/feedbackValidator.js
  client/src/utils/feedbackValidator.test.js
  client/src/utils/scoreEvaluator.js
  client/src/utils/scoreEvaluator.test.js
  e2e/cypress/integration/complete_survey.js
Labels: release

#60 Added analytics
  client/public/index.html
  client/src/App.js
  client/src/components/Result/Feedback.js
  client/src/utils/analytics.js
Labels: enhancement

#61 Feature/remove jquery
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/AgileAssessment.js
Labels: cleanup

#62 v1.2.2
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/AgileAssessment.js
  client/src/components/Result/Feedback.js
  client/src/utils/analytics.js
Labels: release

#63 Update README.md
  README.md
Labels: cleanup

#64 Fixed some css styles
  client/src/components/Result/Link.js
  client/src/components/Result/index.js
  client/src/styles/evaluation.scss
  client/src/styles/index.scss
Labels: cleanup

#66 Minor vulnerability fixes
  client/package-lock.json
  client/package.json
  client/src/components/Footer.js
  server/package-lock.json
Labels: cleanup

#67 Merge footer components
  client/src/App.js
  client/src/components/FootNote.js
  client/src/components/Footer.js
  client/src/config/surveyConfig.js
  e2e/cypress/integration/complete_survey.js
Labels: cleanup

#69 Implement Landing Page
  client/src/App.js
  client/src/components/Result/AgileLinks.react.test.js
  client/src/components/Result/index.js
  client/src/styles/index.scss
  e2e/cypress/integration/complete_survey.js
Labels: enhancement
