Repository enpayne/agile-assessment-tool, pull requests merged in 2019-05, with the labels that each got.

#39 Replaced logo png with svg
  client/src/app/Footer.js
  client/src/assets/images/icons-x2/logo-zuehlke-big.png
  client/src/assets/images/icons-x2/logo-zuehlke-small.png
  client/src/assets/images/icons/logo-zuehlke-big.png
  client/src/assets/images/icons/logo-zuehlke-small.png
  client/src/assets/images/logo-zuehlke-small.png
  client/src/assets/images/logo-zuhlke.svg
Labels: enhancement

#38 Node 12 is not compatible with Sass 4.11
  docker-compose.yml
Labels: bug

#41 Implement eslint rules
  .eslintrc.js
  README.md
  client/src/api.js
  client/src/app/AgileAssessment.js
  client/src/app/App.js
  client/src/app/FootNote.js
  client/src/app/Footer.js
  client/src/app/Header.js
  client/src/app/result/Result.js
  client/src/app/result/evaluation/Evaluation.js
  client/src/app/result/evaluation/scoreEvaluator.js
  client/src/app/result/evaluation/scoreEvaluator.test.js
  client/src/app/result/feedback/Feedback.js
  client/src/app/result/feedback/Feedback.react.test.js
  client/src/app/result/feedback/feedbackValidator.js
  client/src/app/result/feedback/feedbackValidator.test.js
  client/src/app/result/link/Link.js
  client/src/app/result/link/linkProvider.js
  client/src/app/result/link/linkProvider.test.js
  client/src/app/result/profile/Profile.js
  client/src/app/result/profile/profileInformation.js
  client/src/app/surveyconfig/QuestionType.js
  client/src/app/surveyconfig/configGenerator.js
  client/src/app/surveyconfig/configGenerator.test.js
  client/src/index.js
  client/src/registerServiceWorker.js
  client/src/setupTests.js
  package-lock.json
  package.json
  server/src/app.js
  server/src/app.test.js
  server/src/db.js
  server/src/server.js
  server/src/surveys/surveyReader.js
  server/src/surveys/surveyReader.test.js
Labels: refactor

#47 Fix question numbering
  .eslintrc.js
  client/src/app/App.js
  client/src/app/surveyconfig/configGenerator.js
  client/src/app/surveyconfig/configGenerator.test.js
  e2e/cypress/.eslintrc.json
  e2e/cypress/elements/CypressHttpRequest.js
  e2e/cypress/elements/Survey.js
  e2e/cypress/fixtures/testQuestions.js
  e2e/cypress/integration/complete_survey.js
  package-lock.json
  package.json
Labels: bug

#45 Cleanup various client components
  client/package-lock.json
  client/package.json
  client/src/app/AgileAssessment.js
  client/src/app/App.js
  client/src/app/FootNote.js
  client/src/app/Footer.js
  client/src/app/Header.js
  client/src/app/result/Result.js
  client/src/app/result/evaluation/Evaluation.js
  client/src/app/result/profile/Profile.js
  client/src/app/surveyconfig/configGenerator.js
  server/package-lock.json
Labels: cleanup

#51 Upgrade react to 16.8.6
  client/package-lock.json
  client/package.json
Labels: enhancement

#54 Release/v1.1.0
  .eslintrc.js
  README.md
  client/package-lock.json
  client/package.json
  client/src/api.js
  client/src/app/AgileAssessment.js
  client/src/app/App.js
  client/src/app/FootNote.js
  client/src/app/Footer.js
  client/src/app/Header.js
  client/src/app/result/Result.js
  client/src/app/result/evaluation/Evaluation.js
  client/src/app/result/evaluation/scoreEvaluator.js
  client/src/app/result/evaluation/scoreEvaluator.test.js
  client/src/app/result/feedback/Feedback.js
  client/src/app/result/feedback/Feedback.react.test.js
  client/src/app/result/feedback/feedbackValidator.js
  client/src/app/result/feedback/feedbackValidator.test.js
  client/src/app/result/link/Link.js
  client/src/app/result/link/linkProvider.js
  client/src/app/result/link/linkProvider.test.js
  client/src/app/result/profile/Profile.js
  client/src/app/result/profile/profileInformation.js
  client/src/app/surveyconfig/QuestionType.js
  client/src/app/surveyconfig/configGenerator.js
  client/src/app/surveyconfig/configGenerator.test.js
  client/src/assets/images/angular-foundation.png
  client/src/assets/images/angular.png
  client/src/assets/images/base-1x-s016cec0915.png
  client/src/assets/images/base-2x-sede587b392.png
  client/src/assets/images/icons-x2/logo-zuehlke-big.png
  client/src/assets/images/icons-x2/logo-zuehlke-small.png
  client/src/assets/images/icons/logo-zuehlke-big.png
  client/src/assets/images/icons/logo-zuehlke-small.png
  client/src/assets/images/logo-zuehlke-small.png
  client/src/assets/images/logo-zuhlke.svg
  client/src/index.js
  client/src/registerServiceWorker.js
  client/src/setupTests.js
  client/src/styles/index.scss
  e2e/cypress/.eslintrc.json
  e2e/cypress/elements/CypressHttpRequest.js
  e2e/cypress/elements/Survey.js
  e2e/cypress/fixtures/testQuestions.js
  e2e/cypress/integration/complete_survey.js
  package-lock.json
  package.json
  server/package-lock.json
  server/src/app.js
  server/src/app.test.js
  server/src/db.js
  server/src/server.js
  server/src/surveys/surveyReader.js
  server/src/surveys/surveyReader.test.js
Labels: release

#50 Implement changes to Feedback form
  client/src/app/result/feedback/Feedback.js
  client/src/app/result/feedback/Feedback.react.test.js
  client/src/app/result/feedback/feedbackValidator.js
  client/src/app/result/feedback/feedbackValidator.test.js
  client/src/styles/result.scss
Labels: enhancement

#52 Improve progress bars in the results page
  client/package-lock.json
  client/package.json
  client/src/app/result/Result.js
  client/src/app/result/evaluation/Evaluation.js
  client/src/app/result/evaluation/Evaluation.react.test.js
  client/src/app/result/evaluation/categoryInformation.js
  client/src/styles/evaluation.scss
Labels: enhancement

#55 Release/v1.2.0
  client/package-lock.json
  client/package.json
  client/src/app/result/Result.js
  client/src/app/result/evaluation/Evaluation.js
  client/src/app/result/evaluation/Evaluation.react.test.js
  client/src/app/result/evaluation/categoryInformation.js
  client/src/app/result/feedback/Feedback.js
  client/src/app/result/feedback/Feedback.react.test.js
  client/src/app/result/feedback/feedbackValidator.js
  client/src/app/result/feedback/feedbackValidator.test.js
  client/src/styles/evaluation.scss
  client/src/styles/result.scss
Labels: release

#56 Fixed/improved styles
  client/src/app/result/evaluation/Evaluation.js
  client/src/app/result/link/Link.js
  client/src/app/result/profile/Profile.js
  client/src/styles/evaluation.scss
  client/src/styles/result.scss
Labels: cleanup
